### ISSUE TITLE
mount: unknown filesystem type 'minfs'

### ISSUE THREAD

**Issue by paulocoghi** [minio/minfs#13]
**Description:**
When running:

`sudo mount -t minfs http://10.20.30.40:9000/my-bucket /mymount/to/bucket/`

This error is returned:

`mount: unknown filesystem type 'minfs'`

**MinFS version**
Installed today ( 17 Oct 2016 ) using: `go get -u github.com/minio/minfs`

**OS**
Ubuntu Server 16.04.1  64
(updated and upgraded today)

**Comment by harshavardhana** [comment]
@paulocoghi you have to install `mount.minfs` script as well can you do 'make' inside the minfs checkout?

**Comment by harshavardhana** [comment]
Update doc indicating to use `make` instead of 'go get'.
