### ISSUE TITLE
Cannot see new files

### ISSUE THREAD

**Issue by Semyazz** [minio/minfs#14]
It looks like the driver is not notified when new files are created on Minio Server. I have to umount and mount the share again to see new files. Similar thing is when a file is deleted. it no longer can shows the content of the file, because it does not exists on the server, but I can still see it on the filesystem. Is there anything to refresh it?

Changes on the other hand propagate correctly, so the content is correctly synced.

**Comment by harshavardhana** [comment]
This is purposefully not supported. Right now we have no plans to work on this feature.

**Comment by harshavardhana** [comment]
Closing.. this as not going to be fixed.
