### ISSUE TITLE
UID/GID not set

### ISSUE THREAD

**Issue by Semyazz** [minio/minfs#15]
How am I supposed to set UID/GID for mounted shares?

    mount -t minfs http://.../share /mnt -o uid=<NUMBER>,gid=<NUMBER>

doesn't seem to work

**Comment by harshavardhana** [comment]
> How am I supposed to set UID/GID for mounted shares?
> 
> mount -t minfs http://.../share /mnt -o uid=<NUMBER>,gid=<NUMBER>
> doesn't seem to work

what is the error that you see?

**Comment by Semyazz** [comment]
That's the problem. there is no error message, even though there should be something. I'll build and take look at the code and try to figure out what is wrong, but just to confirm. is it working for you with uid/gid?

**Comment by harshavardhana** [comment]
> That's the problem. there is no error message, even though there should be something. I'll build and take look at the code and try to figure out what is wrong, but just to confirm. is it working for you with uid/gid?

Yes it is working @Semyazz - can you provide your operating system details?

**Comment by klee1001** [comment]
Under ubuntu 16.04 I have the same behavior

**Comment by Semyazz** [comment]
I got also Ubuntu 16.04

**Comment by harshavardhana** [comment]
Will try and let you know @Semyazz @klee1001

**Comment by harshavardhana** [comment]
Can you just try without 'mount -t minfs' ? just using the binary directly

```
minfs -o uid=1000,gid=1000 http://localhost:9001/testbucket /mnt/ramdisk &
```

**Comment by klee1001** [comment]
It is still the same

**Comment by harshavardhana** [comment]
> It is still the same

Can you tell me step by step how are you testing it? @klee1001

**Comment by klee1001** [comment]
Very simple:
sudo mkdir /test
sudo chown and chgrp /test
sudo mount -t minfs http://10.87.209.26:9000/test /test -o uid=1000,gid=1000

**Comment by harshavardhana** [comment]
Why is shown and chgrp needed ?

**Comment by klee1001** [comment]
This are the command to set the directory to the uid and gid 1000, but after the mount the directory is change the id back to root

**Comment by harshavardhana** [comment]
> This are the command to set the directory to the uid and gid 1000, but after the mount the directory is change the id back to root

'chown and chgrp' are not needed.. - uid and gid is set for the files inside the mount /test - can you 'touch /test/file' and see?

**Comment by harshavardhana** [comment]
Also btw mount.minfs had a bug which is fixed in latest master not sure if you updated..  You can try directly using `minfs`  directly.

**Comment by klee1001** [comment]
I have tried both with the same result!

**Comment by harshavardhana** [comment]
> I have tried both with the same result!

Can you paste "ls -l" output?

**Comment by harshavardhana** [comment]
```
$ mount -t minfs -ouid=1000,gid=1000 http://10.1.10.162:9002/testbucket /mnt/ramdisk/
$ touch /mnt/ramdisk/test.txt

$ ls -l /mnt/ramdisk/test.txt 
-rw-r--r-- 0 harsha harsha 0 Dec 15 10:58 /mnt/ramdisk/test.txt

$ ls -l /mnt/ramdisk/
total 0
drwxrwx--- 0 harsha harsha 0 Aug 30  1754 1
```

**Comment by harshavardhana** [comment]
Closing.. as working.

**Comment by rremer** [comment]
FYI, I had the same issue until building from #47 , which appears to have resolved this issue.

I was able to replicate with:
minfs version 2017-02-26T20-20-56Z
fusermount version: 2.9.2
