### ISSUE TITLE
Mounting multiple buckets on the same host?

### ISSUE THREAD

**Issue by bearmoo-repo** [minio/minfs#16]
Hi,

I was wondering if its possible to mount multiple buckets on the same host using minfs?

**Comment by harshavardhana** [comment]
> I was wondering if its possible to mount multiple buckets on the same host using minfs?

Yes you can mount multiple buckets to different mount points.

**Comment by bearmoo-repo** [comment]
Ok, So when I try to do so I see this in the log:

MinFS 2017/02/04 20:07:09 fs.go:139: Opening cache database...
MinFS 2017/02/04 20:07:09 fs.go:146: Initializing cache database...
MinFS 2017/02/04 20:07:09 fs.go:154: Initializing minio client...
MinFS 2017/02/04 20:07:09 fs.go:181: Mounting target....
MinFS 2017/02/04 20:07:09 fs.go:204: Mounted... Have fun!
MinFS 2017/02/04 20:08:20 fs.go:139: Opening cache database...

when I do a df, I see this:

MinFS            64T     0   64T   0% /mnt/minfs

command:
mount -t minfs http://x.x.x.x:9000/iso /mnt/iso
mount -t minfs http://x.x.x.x:9000/pic /mnt/pic

**Comment by PDRMAN** [comment]
I am having the same issue, trying to mount multiple buckets on the same host to different mount points. mounting a bucket using mount or creating an entry in fstab works fine, multiple entries cause it to hang. nothing in the logs. here is my commented out fstab:

#http://mylocals3.com/puppet /app/buckets/puppet minfs defaults 0 0
#http://mylocals3.com/bitbucket /app/buckets/bitbucket minfs defaults 0 0
#http://mylocals3.com/bladelogic /app/buckets/bladelogic minfs defaults 0 0
#http://mylocals3.com/data-rpm /app/buckets/data-rpm minfs defaults 0 0
#http://mylocals3.com/dit-confluence/ /app/buckets/dit-confluence/ minfs defaults 0 0
#http://mylocals3.com/hpoo /app/buckets/hpoo minfs defaults 0 0
#http://mylocals3.com/sitescope /app/buckets/sitescope minfs defaults 0 0

**Comment by harshavardhana** [comment]
Can you try this? 

```
http://mylocals3.com/puppet /app/buckets/puppet minfs defaults,cache=/var/lib/minfs/puppet 0 0
http://mylocals3.com/bitbucket /app/buckets/bitbucket minfs defaults,cache=/var/lib/minfs/bitbucket 0 0
http://mylocals3.com/bladelogic /app/buckets/bladelogic minfs defaults,cache=/var/lib/minfs/bladelogic 0 0
http://mylocals3.com/data-rpm /app/buckets/data-rpm minfs defaults,cache=/var/lib/minfs/data-rpm 0 0
http://mylocals3.com/dit-confluence/ /app/buckets/dit-confluence/ minfs defaults,cache=/var/lib/minfs/dit-confluence 0 0
http://mylocals3.com/hpoo /app/buckets/hpoo minfs defaults,cache=/var/lib/minfs/hpoo 0 0
http://mylocals3.com/sitescope /app/buckets/sitescope minfs defaults,cace=/var/lib/minfs/sitescope 0 0
```

Notice the 'cache' path is used for boltdb metadata which needs to be different for each bucket.

**Comment by PDRMAN** [comment]
Thank you, but that only mounted the first bucket. is there a link to the full usage of minfs mount? I

Content of the cache dir:

CDLSTAP02:/var/lib/minfs # l
total 0
drwx------ 1 root root  12 Feb 18 20:34 ./
drwxr-xr-x 1 root root 840 Feb 18 20:34 ../
drwx------ 1 root root  16 Feb 18 20:34 puppet/
CDLSTAP02:/var/lib/minfs #


log file contents: 

MinFS 2017/02/18 20:33:47 fs.go:221: MinFS stopped cleanly.
MinFS 2017/02/18 20:33:47 fs.go:221: MinFS stopped cleanly.
MinFS 2017/02/18 20:34:53 fs.go:134: Mounting target....
MinFS 2017/02/18 20:34:53 fs.go:155: Opening cache database...
MinFS 2017/02/18 20:34:53 fs.go:162: Initializing cache database...
MinFS 2017/02/18 20:34:53 fs.go:170: Initializing minio client...
MinFS 2017/02/18 20:34:53 fs.go:204: Serving... Have fun!

**Comment by harshavardhana** [comment]
it should mount all the buckets in /etc/fstab here is a working example. 


```
MinFS            64T     0   64T   0% /mnt/mounted/testbucket1
MinFS            64T     0   64T   0% /mnt/mounted/testbucket2
MinFS            64T     0   64T   0% /mnt/mounted/testbucket3
MinFS            64T     0   64T   0% /mnt/mounted/testbucket4
```

```
grep minfs /etc/fstab
https://play.minio.io:9000/testbucket1 /mnt/mounted/testbucket1 minfs defaults,cache=/tmp/testbucket1 0 0
https://play.minio.io:9000/testbucket2 /mnt/mounted/testbucket2 minfs defaults,cache=/tmp/testbucket2 0 0
https://play.minio.io:9000/testbucket3 /mnt/mounted/testbucket3 minfs defaults,cache=/tmp/testbucket3 0 0
https://play.minio.io:9000/testbucket4 /mnt/mounted/testbucket4 minfs defaults,cache=/tmp/testbucket4 0 0
```

Don't reach too much into the size itself, since size is ephemeral here object storage has no sense of 'df -h' it is just chosen to be  64TB as a max number out of sane top limit for any given bucket.

Now to test the i/o 

```
touch /mnt/mounted/testbucket{1,2,3,4}/a

ls -l /mnt/mounted/testbucket{1,2,3,4}/a
-rw-r--r-- 0 root root 0 Feb 18 17:55 /mnt/mounted/testbucket1/a
-rw-r--r-- 0 root root 0 Feb 18 17:55 /mnt/mounted/testbucket2/a
-rw-r--r-- 0 root root 0 Feb 18 17:55 /mnt/mounted/testbucket3/a
-rw-r--r-- 0 root root 0 Feb 18 17:55 /mnt/mounted/testbucket4/a
```

Verify on the server
```
mc ls play/testbucket{1,2,3,4}
[2017-02-18 17:55:13 PST]     0B a
[2017-02-18 17:55:13 PST]     0B a
[2017-02-18 17:55:13 PST]     0B a
[2017-02-18 17:55:13 PST]     0B a
```

**Comment by harshavardhana** [comment]
```
root      7829  3851  0 17:53 pts/3    00:00:00 /sbin/minfs -o rw,cache=/tmp/testbucket1 https://play.minio.io:9000/testbucket1 /mnt/mounted/testbucket1
root      7845  3851  0 17:53 pts/3    00:00:00 /sbin/minfs -o rw,cache=/tmp/testbucket2 https://play.minio.io:9000/testbucket2 /mnt/mounted/testbucket2
root      7866  3851  0 17:53 pts/3    00:00:00 /sbin/minfs -o rw,cache=/tmp/testbucket3 https://play.minio.io:9000/testbucket3 /mnt/mounted/testbucket3
root      7887  3851  0 17:53 pts/3    00:00:00 /sbin/minfs -o rw,cache=/tmp/testbucket4 https://play.minio.io:9000/testbucket4 /mnt/mounted/testbucket4
```

**Comment by harshavardhana** [comment]
> Thank you, but that only mounted the first bucket. is there a link to the full usage of minfs mount? I

https://github.com/minio/minfs/blob/master/DESIGN.md#options talks about optional fuse options.

**Comment by PDRMAN** [comment]
Thank you again for the help. I am not getting the expected result. I tried just mounting 2 buckets but it only does the first. I rebooted, cleared out the cache. tried turning on debug logging. What OS are you running on and what version? 

CDLSTAP02:/home/virtual # uname -a
Linux CDLSTAP02 3.12.67-60.64.21-default #1 SMP Fri Dec 2 07:25:10 UTC 2016 (ac54c96) x86_64 x86_64 x86_64 GNU/Linux

CDLSTAP02:/home/virtual # go version
go version go1.7.4 linux/amd64
CDLSTAP02:/home/virtual # go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/go/work"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build367464282=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CDLSTAP02:/home/virtual #

**Comment by harshavardhana** [comment]
> Thank you again for the help. I am not getting the expected result. I tried just mounting 2 buckets but it only does the first. I rebooted, cleared out the cache. tried turning on debug logging. What OS are you running on and what version?

I am using Ubuntu 16.04 (LTS)

```
uname -a
Linux prtsc 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

You might have to use latest kernel not sure if its a fuse problem on your OS.

**Comment by krisis** [comment]
@PDRMAN When mounting multiple buckets on the same host you are required to provide separate cache directory for each of them. Following is a sample fstab entry with cache directory passed as a mount option. This should solve the multiple MinFS mounts hanging issue.

`https://play.minio.io:9000/mybucket /mnt/data minfs defaults,cache=/tmp/data,uid=48,gid=48 0 0`

**Comment by PDRMAN** [comment]
Thank you, yes we tried that and got it working. It would help if this info was captured in the documentation.

**Comment by krisis** [comment]
@PDRMAN you're welcome. This information is available in the fstab example here https://github.com/minio/minfs/blob/master/README.md#mount-mybucket. I am closing this issue since it is working as expected.
