### ISSUE TITLE
Not able to mount multiple volumes using the docker driver minfs

### ISSUE THREAD

**Issue by bearmoo-repo** [minio/minfs#24]
Tring to mount two buckets in the same cantainer, but getting an error:
Error response from daemon: containerd: container did not start before the specified timeout.

Expected Behavior

I should see in the runnung container:
/ # df -h
Filesystem Size Used Available Use% Mounted on
overlay 31.2G 13.2G 16.3G 45% /
tmpfs 919.8M 0 919.8M 0% /dev
tmpfs 919.8M 0 919.8M 0% /sys/fs/cgroup
MinFS 64.0T 0 64.0T 0% /mnt/websites
MinFS 64.0T 0 64.0T 0% /mnt/data
/dev/sda2 31.2G 13.2G 16.3G 45% /etc/resolv.conf
/dev/sda2 31.2G 13.2G 16.3G 45% /etc/hostname
/dev/sda2 31.2G 13.2G 16.3G 45% /etc/hosts
shm 64.0M 0 64.0M 0% /dev/shm
tmpfs 919.8M 0 919.8M 0% /proc/kcore
tmpfs 919.8M 0 919.8M 0% /proc/timer_list
tmpfs 919.8M 0 919.8M 0% /proc/timer_stats
tmpfs 919.8M 0 919.8M 0% /proc/sched_debug
tmpfs 919.8M 0 919.8M 0% /sys/firmware

I should be able to mount multple volumes into a container from the minfs driver.

Current Behavior

Possible Solution

Steps to Reproduce (for bugs)

docker volume create -d minio/minfs --name data -o endpoint=https://example.com:9000 -o access-key=yyyy -o secret-key=xxxx -o bucket=data
docker volume create -d minio/minfs --name websites -o endpoint=https://example.com:9000 -o access-key=yyyy -o secret-key=xxxx -o bucket=websites
3.docker run -it -v data:/mnt/data -v websites:/mnt/websites busybox /bin/sh
Context

I am trying create an environment where data is not limited to a specific area. Moreover have docker mount the needed resources for the container without the need for me to configure the host so that the containers can use the resources.

For example:
Instead of having to configure the host to mount nfs share, I can use minfs driver for docker make that data availble weather its local or on the cloud.

Your Environment

Version used: lastest
Docker version: 1.13.1
Environment name and version (e.g. nginx 1.9.1): busybox
Server type and version: virtual machine(Cloud services)
Operating System and version: Centos 7.2
Link to your project:

**Comment by harshavardhana** [comment]
Thank you.

**Comment by PDRMAN** [comment]
we hit this issue but on a server not on docker, we added the cache parameter which allowed us to mount multiple buckets, add this option  -o cache=/var/lib/minfs/<some_unique_name>

in the docs it doesn't say you need this parameter but you do if you are mounting multiple buckets. minfs will try and use the same cache dir for all buckets which causes a problem.

**Comment by bearmoo-repo** [comment]
Ok. So I add the options cache:

docker volume create -d minio/minfs --name data -o endpoint=https://example.com:9000 -o access-key=yyyy -o secret-key=xxxx -o bucket=data -o cache=/tmp/data

docker volume create -d minio/minfs --name websites -o endpoint=https://example.com:9000 -o access-key=yyyy -o secret-key=xxxx -o bucket=websites -o cache=/tmp/websites

3.docker run -it -v data:/mnt/data -v websites:/mnt/websites busybox /bin/sh

I notice now, it just hangs. Is there another option I can try?

**Comment by harshavardhana** [comment]
Ping @hackintoshrao

**Comment by PDRMAN** [comment]
in our mount script we added a '&' at the end, this basically spawned off a thread and didn't wait for the entire cache to build. see if you can add something similar. 

good luck!

**Comment by bearmoo-repo** [comment]
The & does really address the issue it self. I tried mounting multiple buckets in a container several times and the results follow:

I will ether get a timeout error from infs
It will cause the container to hang.
The container will launch, but the volumes are not mounted in the container.

**Comment by krisis** [comment]
@bearmoo-repo if you create the volumes as below, the `docker run ...` with multiple MinFS volumes doesn't hang and works as expected.

`docker volume create -d minio/minfs --name data -o endpoint=https://example.com:9000 -o access-key=yyyy -o secret-key=xxxx -o bucket=data -o opts=cache=/tmp/data`

`docker volume create -d minio/minfs --name websites -o endpoint=https://example.com:9000 -o access-key=yyyy -o secret-key=xxxx -o bucket=websites -o opts=cache=/tmp/websites`

**Comment by krisis** [comment]
@bearmoo-repo I am closing this issue as resolved. I have updated the README with how to pass cache directory information to minfs.
