### ISSUE TITLE
Directories are not inheriting permissions?

### ISSUE THREAD

**Issue by bearmoo-repo** [minio/minfs#25]
I notice that when I set the permissions for a bucket(in fstab with uid, gid), I notice that the files inherit the permission but not the directories.

https://example.com:9000/ddata      /mnt/data   minfs   defaults,cache=/tmp/data,uid=48,gid=48  0 0
https://example.com:9000/websites /mnt/websites   minfs   defaults,cache=/tmp/websites,uid=48,gid=48    0 0

ls -la:
-rw-rw----. 0   48   48 35 Mar 24 01:59 robots.txt
drwxrwx---. 0 root root  0 Aug 30  1754 speedtest
drwxrwx---. 0 root root  0 Aug 30  1754 webmail

Any idea?

**Comment by harshavardhana** [comment]
> ls -la:
> -rw-rw----. 0 48 48 35 Mar 24 01:59 robots.txt
> drwxrwx---. 0 root root 0 Aug 30 1754 speedtest
> drwxrwx---. 0 root root 0 Aug 30 1754 webmail
> 
> Any idea?

Looks like a bug @bearmoo-repo .

**Comment by krisis** [comment]
@bearmoo-repo I was unable to recreate this issue locally. In my tests, both directories and files inherited the uid, gid provided in the fstab entry. Could you provide the following information to analyse the issue further?

1. Output of `ps ax | grep minfs`
2. Output of `minfs -V`
3. If built from source, commit id.
4. Output of `uname -a`
5. Output of `fusermount -V`

**Comment by bearmoo-repo** [comment]
ps ax | grep minfs
  784 ?        Ssl    0:05 /usr/sbin/minfs-docker-plugin
 1836 ?        Z      0:00 [minfs] <defunct>
 2419 ?        Z      0:00 [minfs] <defunct>
 2890 ?        Sl     0:34 /sbin/minfs -o rw,cache=/tmp/stuff https://example.com:9000/sites /mnt/sites
 2912 ?        Z      0:00 [minfs] <defunct>
 2923 ?        Sl     0:04 /sbin/minfs -o rw,cache=/tmp/stuff https://example.com:9000/stuff /mnt/stuff
 3091 ?        Z      0:00 [minfs] <defunct>
 6322 ?        Sl     0:04 /sbin/minfs -o rw https://example.com:9000/stuff /mnt/stufft_7b8a8
 8272 pts/1    R+     0:00 grep --color=auto minfs
12476 ?        Sl     0:04 /sbin/minfs -o rw,cache=/tmp/sties https://example.com:9000/websites /mnt/sites
12573 ?        Sl     0:04 /sbin/minfs -o rw,cache=/tmp/stuff https://example.com:9000/owncloud /mnt/stuff


minfs -V
minfs version 2017-02-26T20-20-56Z

uname -a
Linux courtyard07 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

fusermount -V
fusermount version: 2.9.2

**Comment by colakong** [comment]
I ran into a similar issue, but when attempting to specify the _uid_, _gid_ at the cli instead of fstab.

```
cedric@gloria /mnt/storage/tmp : ps ax | grep minfs
22965 pts/9    S+     0:00 sudo /home/cedric/bin/minfs -o uid=1000,gid=1000 http://127.0.0.1:9000/test-bucket /mnt/storage/tmp/s3_mount
22966 pts/9    Sl+    0:00 /home/cedric/bin/minfs -o uid=1000,gid=1000 http://127.0.0.1:9000/test-bucket /mnt/storage/tmp/s3_mount
22997 pts/12   S+     0:00 grep --colour minfs
cedric@gloria /mnt/storage/tmp :

cedric@gloria /mnt/storage/tmp : minfs -V
minfs version 2017-04-06T07:42:00Z
cedric@gloria /mnt/storage/tmp :

cedric@gloria /mnt/storage/tmp : uname -a
Linux gloria 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
cedric@gloria /mnt/storage/tmp :

cedric@gloria /mnt/storage/tmp : fusermount -V
fusermount version: 2.9.3
cedric@gloria /mnt/storage/tmp :
```

Actual mount shows uid, gid set to 0
```
cedric@gloria /mnt/storage/tmp : grep -i minfs /proc/mounts 
MinFS /mnt/storage/tmp/s3_mount fuse.MinFS rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
cedric@gloria /mnt/storage/tmp :
```

I looked at the code in `fs/fs.go`, but I didn't see where the _uid_, _gid_ cli args were passed to the `mount()` function.

**Comment by krisis** [comment]
@bearmoo-repo,
>2890 ? Sl 0:34 /sbin/minfs -o rw,cache=/tmp/stuff https://example.com:9000/sites /mnt/sites
2912 ? Z 0:00 [minfs] 

It appears that `uid=48,gid=48` from `/etc/fstab` entry didn't make it to `minfs`'s command-line arguments. When I tried to recreate the issue I see the uid and gid appear in `minfs`'s command-line arguments as expected.
```
root@trantor:~# ps ax | grep minfs
18811 pts/2    Sl     0:00 /sbin/minfs -o rw,cache=/tmp/data,uid=48,gid=48 http://localhost:9000/ddata /mnt/data
```
Could you confirm if the permissions problem remains when you run `/sbin/minfs` binary directly with the same mount options (uid, gid, etc.) like below?
`/sbin/minfs -o rw,cache=/tmp/stuff,uid=48,gid=48 https://example.com:9000/sites /mnt/sites`

**Comment by krisis** [comment]
@colakong,
> Actual mount shows uid, gid set to 0

Directory/file permissions work as expected on my setup. I see uid, gid as 0 as per `/proc/mounts` same as in your setup. But it doesn't affect the behaviour in my case, directories and files are assigned uid and gid as specified in the fstab entry.

>I looked at the code in fs/fs.go, but I didn't see where the uid, gid cli args were passed to the mount() function

The uid, gid mount options are not passed via fuse.Mount function. These options are used in the context of creating a file or a directory, see https://github.com/minio/minfs/blob/master/fs/dir.go#L355.

**Comment by bearmoo-repo** [comment]
@krisis 

I did a clean install of centos 7.2 pulled the lastest rpm for minfs. I tried using /sbin/minfs and I see that it just hangs!?

But when I used mount the command, it works?:
mount -t minfs -o rw,cache=/tmp/stuff,uid=48,gid=48 https://example.com:9000/sites /mnt/sites
drwxrwx---. 0 48 48  0 Aug 30  1754 websites1
drwxrwx---. 0 48 48  0 Aug 30  1754 websites2
-rw-rw----. 0 48 48 35 Mar 23 18:59 robots.txt

Out of curiosity, is it possible to have multiple permission with minfs? For example:
drwxrwx---. 0 0 0  0 Aug 30  1754 websites1
drwxrwx---. 0 100 100  0 Aug 30  1754 websites2
-rw-rw----. 0 48 48 35 Mar 23 18:59 robots.txt

**Comment by krisis** [comment]
@bearmoo-repo 
> I did a clean install of centos 7.2 pulled the lastest rpm for minfs. I tried using /sbin/minfs and I see that it just hangs!?

Could you paste the command with its arguments when `minfs` was found hung?

I don't think it is possible to have more than one `uid, gid` for a given `minfs` mount at a given time. Is there a use-case you have in mind that you can explain? We might be able to address it differently.

**Comment by harshavardhana** [comment]
> I did a clean install of centos 7.2 pulled the lastest rpm for minfs. I tried using /sbin/minfs and I see that it just hangs!?

@bearmoo-repo @krisis `minfs` if run without `mount.minfs` is a foreground process, so it would look like it is hung the terminal but it has mounted itself.  You have to proceed to another terminal to check the mount. 
`mount.minfs` on the other hand daemonizes the `minfs` instead.

**Comment by bearmoo-repo** [comment]
@krisis

An example is when a new/update version of a web application is downloaded where the files are set as 99(nobody) and the data directory is set as 48(httpd). A way around this if the files get automatically set.

@harshavardhana 
Thanks, I did not realize that was the case. Yes, that does work as expected:
-rw-r--r--. 0 48 48  0 Apr 11 11:25 test
drwxrwx---. 0 48 48  0 Aug 30  1754 sites1
drwxrwx---. 0 48 48  0 Aug 30  1754 sites2

**Comment by krisis** [comment]
@bearmoo-repo 
>Thanks, I did not realize that was the case. Yes, that does work as expected:

So, can we close this issue?

>An example is when a new/update version of a web application is downloaded where the files are set as 99(nobody) and the data directory is set as 48(httpd). A way around this if the files get automatically set.

At this point, you wish to add the new uid 99(nobody) to the existing `uid, gid` which `minfs` is mounted with. Is that correct?

**Comment by morph027** [comment]
Testing for nobody:


## ```/etc/fstab```

```
http://minio:9000/test /mnt minfs defaults,uid=99,gid=99,cache=/tmp/test 0 0
```

Mounting works:

```
# mount | grep -i minfs
MinFS on /mnt type fuse.MinFS (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
```

Create a file:

```
# echo "foobar" > /mnt/test
# ll /mnt/
total 0
-rw-r--r-- 0 nobody nobody       7 Apr 14 19:51 test
```

Adding something to the file as nobody:

```
# sudo -u nobody -H echo "barfoo" >> /mnt/test
# cat /mnt/test 
foobar
barfoo
```

Trying to delete file as nobody:

```
# sudo -u nobody rm -f /mnt/test     
rm: cannot remove '/mnt/test': Permission denied
```

**Comment by morph027** [comment]
Also the docker volume plugin does not seem to honor the flags:

```
# docker volume create -d minio/minfs --name test -o endpoint=http://my-test-mino:9000 -o access-key=... -o secret-key=... -o bucket=test -o cache=/tmp/test-cache -o uid=65534 -o -gid=65534
# docker run --rm -it -v test:/test alpine:latest
# grep -i minfs /proc/mounts 
MinFS /test fuse.MinFS rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
```

Docker or minfs issue?

**Comment by krisis** [comment]
@morph027
>Trying to delete file as nobody:

>  \# sudo -u nobody rm -f /mnt/test     
rm: cannot remove '/mnt/test': Permission denied

I haven't had the chance to look into why `rm` is failing with `Permission denied`.

>Also the docker volume plugin does not seem to honor the flags:

To specify cache-directory option to `docker volume create` command, use `-o opts=cache=/path/to/cachedir` instead of `-o cache=/path/to/cachedir`.

**Comment by krisis** [comment]
@morph027 Could you paste contents of `/tmp/nobody.out` on running `sudo -u nobody strace -f -o /tmp/nobody.out rm -f /mnt/test` in your setup when you see this issue?

**Comment by morph027** [comment]
Here you go ;)

```
119   execve("/bin/rm", ["rm", "-f", "/mnt/test"], [/* 14 vars */]) = 0
119   brk(0)                            = 0x61f000
119   mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb7a7601000
119   access("/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
119   open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
119   fstat(3, {st_mode=S_IFREG|0644, st_size=11494, ...}) = 0
119   mmap(NULL, 11494, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb7a75fe000
119   close(3)                          = 0
119   open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
119   read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\34\2\0\0\0\0\0"..., 832) = 832
119   fstat(3, {st_mode=S_IFREG|0755, st_size=2118128, ...}) = 0
119   mmap(NULL, 3932672, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fb7a7022000
119   mprotect(0x7fb7a71d8000, 2097152, PROT_NONE) = 0
119   mmap(0x7fb7a73d8000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b6000) = 0x7fb7a73d8000
119   mmap(0x7fb7a73de000, 16896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb7a73de000
119   close(3)                          = 0
119   mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb7a75fd000
119   mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb7a75fb000
119   arch_prctl(ARCH_SET_FS, 0x7fb7a75fb740) = 0
119   mprotect(0x7fb7a73d8000, 16384, PROT_READ) = 0
119   mprotect(0x60d000, 4096, PROT_READ) = 0
119   mprotect(0x7fb7a7602000, 4096, PROT_READ) = 0
119   munmap(0x7fb7a75fe000, 11494)     = 0
119   brk(0)                            = 0x61f000
119   brk(0x640000)                     = 0x640000
119   brk(0)                            = 0x640000
119   ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
119   newfstatat(AT_FDCWD, "/mnt/test", {st_mode=S_IFREG|0644, st_size=14, ...}, AT_SYMLINK_NOFOLLOW) = 0
119   unlinkat(AT_FDCWD, "/mnt/test", 0) = -1 EACCES (Permission denied)
119   open("/usr/lib64/charset.alias", O_RDONLY|O_NOFOLLOW) = -1 ENOENT (No such file or directory)
119   write(2, "rm: ", 4)               = 4
119   write(2, "cannot remove '/mnt/test'", 25) = 25
119   write(2, ": Permission denied", 19) = 19
119   write(2, "\n", 1)                 = 1
119   lseek(0, 0, SEEK_CUR)             = -1 ESPIPE (Illegal seek)
119   close(0)                          = 0
119   close(1)                          = 0
119   close(2)                          = 0
119   exit_group(1)                     = ?
119   +++ exited with 1 +++
```

**Comment by morph027** [comment]
quick test setup:

```
mkdir -p /tmp/export
docker run -d -p 9000:9000 --name minio -e MINIO_ACCESS_KEY=0U6DFZIMS12XV2SVWPUP -e MINIO_SECRET_KEY=Vtn9H4HrTzwImsPVnFXC3yNiYp/blwHn89pU4UCT -v /tmp/export:/export minio/minio server /export
docker run --rm -it --privileged --link minio centos:7 /bin/bash
yum -y install sudo https://github.com/minio/minfs/releases/download/RELEASE.2017-02-26T20-20-56Z/minfs-0.0.20170226202056-1.x86_64.rpm
echo "http://minio:9000/test /mnt minfs defaults,uid=99,gid=99,cache=/tmp/test 0 0" >> /etc/fstab
echo '{"version":"1","accessKey":"0U6DFZIMS12XV2SVWPUP","secretKey":"Vtn9H4HrTzwImsPVnFXC3yNiYp/blwHn89pU4UCT"}' > /etc/minfs/config.json
mount /mnt
```
