### ISSUE TITLE
ARM support for MinFS

### ISSUE THREAD

**Issue by rusher81572** [minio/minfs#26]
Hello, Minfs does not currently work on the ARM cpu architecture. When you install from source, it will say "module not found". It would be good to support both x86 and ARM.

**Comment by lavvy** [comment]
Any progress?

**Comment by powareverb** [comment]
I guess multiarch support for the upstream golang image would help, but not sure of state of this.  Very keen to see this also.

**Comment by harshavardhana** [comment]
We have decided that MinFS will only support amd64 for now, ARM support if needed should be built from source.
