### ISSUE TITLE
Unable to remove docker volume when attached to non-zero exit container

### ISSUE THREAD

**Issue by morph027** [minio/minfs#29]
Steps to reproduce:

* Create a docker volume against any bucket: ```docker volume create -d minio/minfs --name test -o endpoint=http://my-test-minio:9000 -o access-key=... -o secret-key=... -o bucket=test -o cache=/tmp/test-cache```

```bash
$ docker volume  inspect test 
[
    {
        "Driver": "minio/minfs:latest",
        "Labels": {},
        "Mountpoint": "/mnt/test",
        "Name": "test",
        "Options": {
            "access-key": "...",
            "bucket": "test",
            "cache": "/tmp/test-cache",
            "endpoint": "http://my-test-minio:9000",
            "secret-key": "..."
        },
        "Scope": "local"
    }
]

```

* Run a container with this volume: ```docker run --name test -d -v test:/var/lib/postgresql/data postgres:alpine```
* Stop and remove the container: ```docker stop test && docker rm test```
* Try to remove the volume: ```docker volume rm test```

```
Error response from daemon: unable to remove volume: remove test: volume is in use - [some-long-hash]
```

I can still see MinFS mounts:

```
$ mount|grep -i minfs
MinFS on /var/lib/docker/plugins/7683aad85f1097cc07400720293a3fdcddac41843a8574e165124dc5a4ccf3a5/rootfs/mnt/test type fuse.MinFS (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
MinFS on /var/lib/docker/plugins/7683aad85f1097cc07400720293a3fdcddac41843a8574e165124dc5a4ccf3a5/propagated-mount/test type fuse.MinFS (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
MinFS on /var/lib/docker/plugins/7683aad85f1097cc07400720293a3fdcddac41843a8574e165124dc5a4ccf3a5/propagated-mount/test type fuse.MinFS (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
```

**Comment by morph027** [comment]
Ok, seems only to happen with non-zero exiting containers. In this case because postgres' chown fails.

**Comment by morph027** [comment]
Probably an issue with docker itself?

**Comment by krisis** [comment]
@morph027, to pass on cache directory to MinFS while using docker volume plugin is as below,
`docker volume create -d minio/minfs --name test -o endpoint=http://my-test-minio:9000 -o access-key=... -o secret-key=... -o bucket=test -o opts=cache=/tmp/test-cache`

This is documented here - https://github.com/minio/minfs/blob/master/README.md#using-docker
You are not the first user who expected `-o cache=/path/to/cachedir`. Maybe, we should change the plugin to take `cache` as the option name instead of `opts`.

@harshavardhana do you think we can add a separate option in docker volume plugin for cache-directory, since it is not really optional for MinFS?

**Comment by morph027** [comment]
Ok, thanks. But still the same error, probably not related to the cache dir?

**Comment by krisis** [comment]
@morph027 I am able to recreate the issue locally, this is a bug.

**Comment by morph027** [comment]
*piuh* Glad it's no pebkac ;)

Let me know if i can help you with more testing!

**Comment by koolhead17** [comment]
@morph027 We will always need community contribution, keep testing & filing issues. 😄

**Comment by holgerstolzenberg** [comment]
Can confirm that one.

**Comment by morph027** [comment]
Any progress or news? I'd really like to go further with Minio for our Docker Swarm ;)

**Comment by harshavardhana** [comment]
> Any progress or news? I'd really like to go further with Minio for our Docker Swarm ;)

**Comment by morph027** [comment]
Great :+1: ... just ping me if you need any help testing or debugging or everything else except coding ;)

**Comment by harshavardhana** [comment]
Can you validate and let us know if this issue is fixed by `docker plugin install minio/minfs:edge` ? - thanks.

**Comment by morph027** [comment]
Sorry, been busy lately...will throw it at my test bed tonight and let you know...
