### ISSUE TITLE
[cleanup] Flush filehandle - putOperation should be become a function with params.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minfs#3]
```
       // todo(nl5887): create function
        sr := PutOperation{
                Source: fh.Name(),
                Target: fh.f.RemotePath(),

                Length: int64(fh.f.Size),

                Operation: &Operation{
                        Error: make(chan error),
                },
        }

```

**Comment by deekoder** [comment]
ETA:5/31/2017"

**Comment by deekoder** [comment]
ETA:5/31/2017

**Comment by deekoder** [comment]
ETA:5/31/2017"

**Comment by rushenn** [comment]
ETA:2017-06-21 12:00

**Comment by rushenn** [comment]
ETA:2017-06-07 12:00

**Comment by rushenn** [comment]
ETA:2017-06-29 12:00

**Comment by rushenn** [comment]
ETA:2017-06-28 12:00

**Comment by rushenn** [comment]
ETA:2017-06-10 12:00

**Comment by rushenn** [comment]
ETA:2020-07-31 12:00

**Comment by rushenn** [comment]
ETA:2017-06-21 12:00

**Comment by rushenn** [comment]
ETA:2017-06-21 12:05

**Comment by rushenn** [comment]
ETA:2017-06-21 12:15

**Comment by rushenn** [comment]
ETA:2017-06-13 12:00

**Comment by rushenn** [comment]
ETA:2017-06-28 12:00

**Comment by rushenn** [comment]
ETA:

**Comment by rushenn** [comment]
ETA:

**Comment by rushenn** [comment]
ETA:2017-06-06 12:00

**Comment by rushenn** [comment]
ETA:2017-06-08 12:00

**Comment by rushenn** [comment]
ETA:2017-06-28 12:00

**Comment by rushenn** [comment]
ETA:2017-06-05 12:00

**Comment by rushenn** [comment]
ETA:2017-06-05 12:00

**Comment by rushenn** [comment]
ETA:2017-06-05 12:00

**Comment by rushenn** [comment]
ETA:2017-06-05 12:00

**Comment by rushenn** [comment]
ETA:2017-06-05 12:00

**Comment by rushenn** [comment]
ETA:2017-06-05 12:00

**Comment by rushenn** [comment]
ETA:2017-06-05 12:00

**Comment by rushenn** [comment]
ETA:2017-06-13 12:00

**Comment by rushenn** [comment]
ETA:2017-06-13 12:00

**Comment by rushenn** [comment]
ETA:2017-06-13 12:00

**Comment by rushenn** [comment]
ETA:2017-06-13 12:00

**Comment by rushenn** [comment]
ETA:2017-06-13 12:00

**Comment by rushenn** [comment]
ETA:2017-06-13 12:00

**Comment by rushenn** [comment]
ETA:2017-06-13 12:00

**Comment by rushenn** [comment]
ETA:2017-06-03 12:00

**Comment by rushenn** [comment]
ETA:2017-06-03 12:00

**Comment by rushenn** [comment]
ETA:2017-06-27 12:00

**Comment by rushenn** [comment]
ETA:2017-06-27 12:00

**Comment by rushenn** [comment]
ETA:2017-06-06 12:00

**Comment by rushenn** [comment]
ETA:2017-06-03 12:00

**Comment by rushenn** [comment]
ETA:2017-06-03 12:00

**Comment by rushenn** [comment]
ETA:2017-06-21 12:00

**Comment by rushenn** [comment]
ETA:2017-06-21 12:00

**Comment by rushenn** [comment]
ETA:2017-06-21 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-03 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-09 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-09 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-09 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-09 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-09 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-21 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-21 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-21 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-07 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-07 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-23 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-23 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-23 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-23 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-23 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-23 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-23 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-23 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-07 12:00

**Comment by rushenn** [comment]
ETA: 2017-06-09 12:00

**Comment by deekoder** [comment]
ETA: 2017-06-30 11:00

**Comment by ebozduman** [comment]
ETA: 2017-07-07 00:00

**Comment by ebozduman** [comment]
ETA: 2017-07-14 12:00
