### ISSUE TITLE
symbolic links?

### ISSUE THREAD

**Issue by bearmoo-repo** [minio/minfs#33]
I notice that when I tried to copy a directory with symbolic links, I see these errors:

cp: cannot create symbolic link ‘./webmail/vendor/bin/rcubeinitdb.sh’: Input/output error
cp: cannot create symbolic link ‘./webmail/vendor/bin/peardev’: Input/output error

Is this expected?

**Comment by harshavardhana** [comment]
Symlinks are not yet supported on minfs

**Comment by bearmoo-repo** [comment]
Out of curiosity, Is there a time frame when it will be supported?

**Comment by deekoder** [comment]
Will let you know in a day or so @bearmoo-repo

**Comment by bearmoo-repo** [comment]
Ok thanks.

**Comment by deekoder** [comment]
We will prioritize supporting S3 related compatibility items first in our roadmap.

**Comment by gjonespf** [comment]
Also keen to see this added, this is already a suber useful tool however.
OT but @deekoder you mention a roadmap, but there's no project under this project to show a roadmap? Or do you have a trello board set up for this.

**Comment by harshavardhana** [comment]
Symlink support is out of scope for `minfs`  . MinFS is not going to implement fully POSIX compatible filesystem its scope is only meant for limited use cases.
