### ISSUE TITLE
docker-plugin can't verify certificate

### ISSUE THREAD

**Issue by pengu-fr** [minio/minfs#34]
Hi,

I use an nginx proxy in front of 4 distributed minio server in a docker environnement.
I use a self-signed certificated for the proxy.
In this configuration, the webinterface works, mc too (using --insecure), but minfs refuse to connect the proxy, due to the self-signed certificate : 

May  2 17:09:36 haku dockerd[28634]: time="2017-05-02T17:09:36+02:00" level=info msg="time=\"2017-05-02T15:09:36Z\" level=fatal msg=\"Put https://minio-proxy:443/client-ab/: x509: certificate signed by unknown authority\" bucket=client-ab endpoint=\"https://minio-proxy:443\" opts=\"cache=/tmp/my-test-store\" " plugin=b86c6eaf3312cfc73ad70cc8345622fa639877f13e45944f60eb53e938c66caf

Is there an option to bypass certificate verification or to pass a CA certificate to the plugin ?

Thank you,

**Comment by harshavardhana** [comment]
Right now minfs might not have an insecure way to do this like mc. We will fix it.. Thanks for the issue @pengu-fr
