### ISSUE TITLE
Performance/Best Practice considerations?

### ISSUE THREAD

**Issue by bearmoo-repo** [minio/minfs#35]
I am looking at using minio + minfs + docker to possibility host owncloud. I notice that sometimes loading a page it takes a while(up to a minute) when using minfs and minio. I was wondering if there are any recommendation?  My setup so Far:

minio instances running on a vm (2.3GHz w/1.7GiB RAM, 5 100M luns(To use Erasure coding)) => haproxy for the two minio instance => Docker with minfs that is mounting a bucket so serve webpages.

**Comment by krishnasrinivas** [comment]
@bearmoo-repo so are you using minio to host static website?

**Comment by bearmoo-repo** [comment]
Yes.

**Comment by harshavardhana** [comment]
> minio instances running on a vm (2.3GHz w/1.7GiB RAM, 5 100M luns(To use Erasure coding)) => haproxy for the two minio instance => Docker with minfs that is mounting a bucket so serve webpages.

- What is the network connection bandwidth between minfs and minio cluster, you can use `iperf`.  
- How often do you see this delay? is it consistent with a specific pattern?
- Can you share your erasure coding setup and also haproxy config?

**Comment by bearmoo-repo** [comment]
What is the network connection bandwidth between minfs and minio cluster, you can use iperf.:

[root@courtyard02 sysops]# iperf -c 10.10.2.4
------------------------------------------------------------
Client connecting to 10.10.2.4, TCP port 5001
TCP window size: 45.0 KByte (default)
------------------------------------------------------------
[  3] local 10.10.2.6 port 58108 connected with 10.10.2.4 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1.13 GBytes   973 Mbits/sec

[root@cellar01 sysops]# iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
[  4] local 10.10.2.4 port 5001 connected with 10.10.2.6 port 58108
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.0 sec  1.13 GBytes   971 Mbits/sec

How often do you see this delay? is it consistent with a specific pattern?
pretty freequent, and consistance weather I do an ls, or even openning a file in an editor.

Can you share your erasure coding setup and also haproxy config?
Haproxy:
===============================================================
root@add037ca6aff:/# cat /etc/haproxy/haproxy.cfg 
global
    chroot /var/lib/haproxy
    daemon
    group haproxy
    maxconn 4096
    maxpipes 1024
    ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
    ssl-default-bind-options no-sslv3 no-tlsv10
    ssl-default-server-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
    tune.ssl.default-dh-param 2048
    user haproxy

defaults
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http
    maxconn 4096
    mode tcp
    option forwardfor
    option http-server-close
    option redispatch
    retries 3
    timeout client 50000
    timeout connect 5000
    timeout server 50000

resolvers rancher
 nameserver dnsmasq 169.254.169.250:53

listen default
bind *:42

frontend 9000
bind *:9000 ssl crt /etc/haproxy/certs/current
mode http
default_backend 9000_

backend 9000_
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
    http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
    http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_proto
    cookie storage insert indirect nocache domain example.com
mode http
server 51941373945c4e3607fbe788029f230604d290c3 10.42.214.203:9000  cookie 51941373945c4e3607fbe788029f230604d290c3
server 464352680d97821fcd201394280633002332f0e9 10.42.157.201:9000  cookie 464352680d97821fcd201394280633002332f0e9


Erasure:
===============================================================
5/7/2017 10:16:00 PMWaiting for all hosts to resolve.......All hosts are resolving proceeding to initialize Minio.
5/7/2017 10:16:00 PMCreated minio configuration file successfully at /root/.minio
5/7/2017 10:16:01 PM
5/7/2017 10:16:01 PM
5/7/2017 10:16:01 PMInitializing data volume.
5/7/2017 10:16:01 PM[01/04] http://head-node01:9000/export1 - 100 GiB online
5/7/2017 10:16:01 PM[02/04] http://head-node01:9000/export2 - 100 GiB online
5/7/2017 10:16:01 PM[03/04] http://head-node02:9000/export3 - 100 GiB online
5/7/2017 10:16:01 PM[04/04] http://head-node02:9000/export4 - 100 GiB online
5/7/2017 10:16:03 PM
5/7/2017 10:16:03 PMEndpoint:  http://10.42.214.203:9000  http://127.0.0.1:9000
5/7/2017 10:16:03 PMAccessKey: xxx 
5/7/2017 10:16:03 PMSecretKey: yyy 
5/7/2017 10:16:03 PMRegion:    us-east-1
5/7/2017 10:16:03 PMSQS ARNs:  <none>
5/7/2017 10:16:03 PM
5/7/2017 10:16:03 PMBrowser Access:
5/7/2017 10:16:03 PM   http://10.42.214.203:9000  http://127.0.0.1:9000
5/7/2017 10:16:03 PM
5/7/2017 10:16:03 PMCommand-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
5/7/2017 10:16:03 PM   $ mc config host add myminio http://10.42.214.203:9000 xxx yyy
5/7/2017 10:16:03 PM
5/7/2017 10:16:03 PMObject API (Amazon S3 compatible):
5/7/2017 10:16:03 PM   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
5/7/2017 10:16:03 PM   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
5/7/2017 10:16:03 PM   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
5/7/2017 10:16:03 PM   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
5/7/2017 10:16:03 PM
5/7/2017 10:16:03 PMDrive Capacity: 170 GiB Free, 200 GiB Total
5/7/2017 10:16:03 PMStatus:         4 Online, 0 Offline. We can withstand [2] more drive failure(s).

Command:
server http://head-node01/export1 http://head-node01/export2 http://head-node02/export3 http://head-node02/export4

**Comment by bearmoo-repo** [comment]
Also, Would it it affect it minfs if there were dynamic page?

**Comment by harshavardhana** [comment]
> Also, Would it it affect it minfs if there were dynamic page?

I do not think so it would affect, depends on how the locking is being performed.  MinFS holds a single lock on the file for simplicity i.e all other concurrent i/o is blocked on a given file. Say if your application does concurrent writes and reads then they will be serialized so application might see that its slow. 

From the network perf results it doesn't look like there are any system configuration problems. Do you have  any workload profile that we can generate and validate on our end?

**Comment by bearmoo-repo** [comment]
a few right now. Using owncloud and roundcube with apache and docker registry on top of minfs.

**Comment by bearmoo-repo** [comment]
Any update?

**Comment by sokratisg** [comment]
@bearmoo-repo have you managed solving this one? Thinking about the same setup although I'm going to switch Rancher's haproxy with traefik+nginx.

**Comment by bearmoo-repo** [comment]
No, I have not. As I do not have time. For the time being I sticking with Rancher's haproxy because there is a letsencrypt plugin that updates the certs in the cert store and that it propagates the new cert to the load balances.
