### ISSUE TITLE
minfs running on two different hosts are not seeing the same contents in a bucket?

### ISSUE THREAD

**Issue by bearmoo-repo** [minio/minfs#37]
Hi,

I notice that on host01, I see this:

ls:

webmail owncloud test

On host02, I see this:
ls:

webmail owncloud

Is there something that I am missing?

**Comment by harshavardhana** [comment]
Yes they don't see because this functionality is not implemented yet.

**Comment by ToasterKTN** [comment]
I was confused by this behavior also. 

It seems to get kind of resynced, when container are restarted.

**Comment by beniwtv** [comment]
Yeah, this missing functionality makes it impossible currently to run two containers on two hosts for load-balancing with the same MinFS volume.

**Comment by akhmadfld** [comment]
Any estimation time to implement this functionality?

**Comment by morph027** [comment]
Interested too ;)
