### ISSUE TITLE
open /var/log/minfs.log: permission denied

### ISSUE THREAD

**Issue by zeroth** [minio/minfs#38]
Hi,
I am trying to auto mount my s3 bucket using minfs in my /etc/fstab i have added following 
`https://s3.amazonaws.com/mybucket /mnt/bucket/mybucket minfs defaults,auto,uid=1000,gid=1000,user,exec,cache=/tmp/mybucket 0 0`

it doesn't auto mount and when i do 
`$ mount /mnt/bucket/mybucket`
I get `minfs: <ERROR> Unable to instantiate a new minfs open /var/log/minfs.log: permission denied`
is there any way to work around this ?
thanks

**Comment by zeroth** [comment]
Quick update so I manually created and changed the permission for minfs.log as well as catch db ... after this it get mounted but then the owner ship of /mnt/bucket/mybucket is root so the non root users can not write in to the directory I tried changing the owner after mounting it doesn't change.

I have a simple script which moves the files to a target dir but I dont want to run that script as root.
And because /mnt/bucket/mybucket is own by root user my scirpt fails.

Please suggest the proper way to achieve this.

**Comment by fwessels** [comment]
The proper way to configure minfs is to create "home" directories for the different users in the root folder of the mount and give these home directories the appropriate permissions for the designated user(s).

Ordinary users should not write to the root of the mount but instead always inside (or under) their home directory.

**Comment by deekoder** [comment]
Closing this. Please reopen if you think we need to address this further.
