### ISSUE TITLE
Docker plugin performances, data management and further questions

### ISSUE THREAD

**Issue by BastienAr** [minio/minfs#39]
I'm a bit interrogative about data management of this driver.

## Setup

**Minio server**
Docker stack with 4 replicas and a nginx loadbalancer

**Minfs volumes** 
I've followed the README and managed to create a docker volume with :
```
docker volume create -d minio/minfs \                                                                                          
--name my-test-store \
-o endpoint=http://minio-loadbalancer-endpoint \
-o access-key=******* \
-o secret-key=************** \
-o bucket=testbucket -o opts=cache=/tmp/testbucket
```
in addition to a nginx test container:
```
docker run -d --name my-test-server -p 606:80 -v my-test-store:/usr/share/nginx/html nginx
```

## Data management 
If I run a `docker inspect my-test-server` I got : 
```
...

        "Mounts": [
            {
                "Type": "volume",
                "Name": "my-test-store-2",
                "Source": "/var/lib/docker/plugins/8d608d0174e8fc29d0359b14f02774b2ad7e3eafca6aed8be4969818d2d0355f/rootfs/mnt/my-test-store-2",
                "Destination": "/usr/share/nginx/html",
                "Driver": "minio/minfs:latest",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
....
```

which surprised me. 

Why do I get a local mount point ("/var/lib/docker/plugins/8d608d0174e8fc29d0359b14f02774b2ad7e3eafca6aed8be4969818d2d0355f/rootfs/mnt/my-test-store-2") while I previously set _/tmp/testbucket_ as cache ? 
When I create a random file on **my-test-server** container, it appears both on minio (web interface and volumes mounted as export on minio stack) **and** in /var/lib/..., but not in /tmp/testbucket (this directory not even exists). So what's the point of specifying a cache path ? 
   
Also, /var/lib/... replicates **all** the files of my container. I found it less useful if I get two copies (local and on object storage) of each of my volumes. Is this the intended behaviour or did I miss something ?

## Performances
~~I get really bad performances on i/o operations on the minfs volume.~~ (see [edit](##edit))

**write**
```
root@ea455acac38f:/usr/share/nginx/html# time echo "TEEEEST" > test.txt

real	0m5.070s
user	0m0.000s
sys	0m0.000s

root@ea455acac38f:/usr/share/nginx/html# time echo "TEEEEST" > /home/test.txt

real	0m0.000s
user	0m0.000s
sys	0m0.000s
root@ea455acac38f:/usr/share/nginx/html# 
``` 

**read**
```
root@ea455acac38f:/usr/share/nginx/html# time cat test.txt 
TEEEEST

real	0m2.131s
user	0m0.000s
sys	0m0.000s

root@ea455acac38f:/usr/share/nginx/html# time cat /home/test.txt 
TEEEEST

real	0m0.001s
user	0m0.000s
sys	0m0.000s
```

I didn't try connecting directly to a single minio server (without the loadbalancer).

I also get a limit of 1M per file but I this is due to nginx limitation (1Mio upload by default), I will update my conf and retry

## Edit
My bad, I din't [rtfm](https://docs.minio.io/docs/setup-nginx-proxy-with-minio) before configuring nginx loadbalancer. You need to add _proxy_buffering off;_ in your server block in order to get decent I/O perf (read 0.00s, write 0m0.002s for the same test). I leave the paragraph about perf, to help the bad doc readers like me... 

## Conclusion
I would like to know if I missed some things, or if I'm right on my tests and suppositions.

**Comment by BastienAr** [comment]
Is there some update about docker volume management ?

**Comment by harshavardhana** [comment]
MinFS is not meant for performance and should be used for minimal use cases. We will mention this specifically in README.md. If performance is the concern a more feature rich volume drivers should be used such as portworx etc.
