### ISSUE TITLE
Update https://hub.docker.com/r/minio/minfs/

### ISSUE THREAD

**Issue by arthurlogilab** [minio/minfs#40]
On https://hub.docker.com/r/minio/minfs/ the README points to https://github.com/minio/minfs-docker-plugin which doesn't exist anymore. I guess this is the new repo, if so maybe the documentation (and the image) should be updated  ? Or at least explain it is deprecated or has moved.

**Comment by deekoder** [comment]
will do @arthurlogilab

**Comment by harshavardhana** [comment]
Fixed and updated closing this issue.
