### ISSUE TITLE
Use more recent golang image

### ISSUE THREAD

**Issue by arthurlogilab** [minio/minfs#41]
https://github.com/minio/minfs/search?utf8=%E2%9C%93&q=wheezy&type=

Wheezy is pretty old. Stretch just came out. At least jessie should be used

cf https://hub.docker.com/_/golang/

**Comment by harshavardhana** [comment]
Any specific problem with Wheezy?

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/minfs/pull/58
