### ISSUE TITLE
Giving access to docker volumes created with minio to non-root users

### ISSUE THREAD

**Issue by barrachri** [minio/minfs#42]
Currently creating a docker volume with this:

```
docker volume create -d minio/minfs \
  --name minio-volume \
  -o endpoint=http://0.0.0.0:9000 \
  -o access-key=PGSVKWYM1YKOH108X3G6 \
  -o secret-key=lybVEDOhXftL0XbWLx2yaP8+w5L8rk2U91TkfXEP \
  -o bucket=test-2 \
  -o opts=cache=/tmp/my-test-store,uid=1000
```
doesn't give access to non-root user (with uid=1000) to the volume.
You can see the files but you can't create/modify.

The use case is to be able to use minio with docker containers running with a non-root user.

**Comment by cormander** [comment]
I can confirm that passing `-o opts="uid=999,gid=999"` to the `docker volume create` doesn't actually set the uid/gid, nor does passing `volume-opt=uid=999` to the `--mount` flag either.

**Comment by harshavardhana** [comment]
I am able to set this properly 

@cormander @barrachri 

```
$ docker inspect my-test-store
[
    {
        "Driver": "minio/minfs:latest",
        "Labels": {},
        "Mountpoint": "/mnt/my-test-store",
        "Name": "my-test-store",
        "Options": {
            "access-key": "Q3AM3UQ867SPQQA43P2F",
            "bucket": "testbucket",
            "endpoint": "https://play.minio.io:9000",
            "opts": "cache=/tmp/my-test-store,uid=1000,gid=1000",
            "secret-key": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
        },
        "Scope": "local"
    }
]
$ docker run -it --rm --name my-test-server -v my-test-store:/export ubuntu /bin/bash
root@ca3d8addcc43:/# df -h /export
Filesystem      Size  Used Avail Use% Mounted on
MinFS            64T     0   64T   0% /export
root@ca3d8addcc43:/# cd /export/
root@ca3d8addcc43:/export# ls -ltr
total 0
-rw-rw---- 0 1000 1000 537 Aug  6 13:42 50x.html
-rw-rw---- 0 1000 1000 612 Aug  6 13:42 index.html
drwxrwx--- 0 1000 1000   0 Aug  6 21:15 a
-rw-rw---- 0 1000 1000   0 Aug  6 23:51 file
```

**Comment by cormander** [comment]
Yes the files are properly owned, but not the mounted directory itself. Can't create new files at the base directory.

**Comment by harshavardhana** [comment]
You should create a sub directory - of course top level cannot be owned this is the expected behavior for all network mounts.

**Comment by cormander** [comment]
Thanks - that worked.

**Comment by holgerstolzenberg** [comment]
I am currently evaluating Docker storage backends and Minio really looked promising until I stumbled upon this issue.

The scenario I tried to evaluate is to run a Postgres database against a Minio Backend on a single node Swarm cluster using two compose files (one for minio rolled out first, the second one the postgres stack).

I previously did the same with Portainer having Minio as storage backend and it worked like charm.

Now - as the Postgres image tries to change the ownership of the mounted Minio volume, things break. I was not able to work around this and your suggested workaround with sub directories is not applicable for many reasons. In fact - as there are lots of services out there that behave exactly like Postgres (e.g. MySQL, Mongo) - sadly Minio does not suit as backend for them currently.

Any solution to this is really appreciated as this is currently the only thing that holds us back from using Minio. If I have overseen some practical workaround to this, please redirect myself.

I´ll attach a Bash script that showcases the problem.

**Comment by holgerstolzenberg** [comment]
#!/bin/bash

# Overcome some issues using fish shell
SHELL=bash

# create the single node swarm machine
docker-machine create -d virtualbox \
    --virtualbox-cpu-count "2" \
    --virtualbox-memory "1024" \
    --virtualbox-ui-type "headless" \
    postgres-machine

# source environment variables
eval $(docker-machine env postgres-machine)

# Get machine IP
MINIO_IP=$(docker-machine ip postgres-machine)

# install minio/minfs plugin
docker-machine ssh postgres-machine \
  docker plugin install --grant-all-permissions minio/minfs

# initialize swarm mode
docker-machine ssh postgres-machine \
  docker swarm init \
    --listen-addr ${MINIO_IP} \
    --advertise-addr ${MINIO_IP}

# create access keys
MINIO_ACCESS_KEY=$(openssl rand -hex 10)
MINIO_SECRET_KEY=$(openssl rand -hex 15)

# create overlay network
docker network create --driver overlay postgres-network

# create local volumes for minio-server
docker volume create --driver local minio-config
docker volume create --driver local minio-data

# create a minio server at first
docker service create -d \
  --name minio \
  --replicas 1 \
  --network postgres-network \
  -p 9000:9000  \
  --mount "type=volume,src=minio-data,dst=/storage" \
  --mount "type=volume,src=minio-config,dst=/root/.minio" \
  -e "MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}" \
  -e "MINIO_SECRET_KEY=${MINIO_SECRET_KEY}" \
  minio/minio server /storage

# wait for service to spin up
echo ""
echo ">> Waiting for Minio to come up (may take a while)..."
while ! nc -z ${MINIO_IP} 9000; do   
  sleep 1
done

echo ">> Minio service logs"
docker service logs minio

# then create a volume to back up Postgresql data
echo ""
echo ">> Create Postgres volume ..."
docker volume create \
  -d minio/minfs \
  --name postgres-data \
  -o endpoint=http://${MINIO_IP}:9000 \
  -o access-key=${MINIO_ACCESS_KEY} \
  -o secret-key=${MINIO_SECRET_KEY} \
  -o bucket=postgres-data 
  # -o opts=uid=999,gid=999

# lanuch the Postgres server and connect to minio
echo ""
echo ">> Starting Postgres server ..."
docker service create -d \
  --name postgres \
  --replicas 1 \
  --network postgres-network \
  -p 5432:5432  \
  --mount "type=volume,src=postgres-data,dst=/var/lib/postgresql/data" \
  -e "POSTGRES_USER=admin" \
  -e "POSTGRES_PASSWORD=changeit" \
  postgres:9.6.4-alpine

echo ""
echo "Now look into the service logs of postgres and you´ll find the error."

**Comment by morph027** [comment]
In the same boat here...using a subfolder and define `PGDATA` to it of the volume brings me some steps further.

**Comment by harshavardhana** [comment]
Can you explain what crashes @morph027 ? is it your app or minfs?

**Comment by morph027** [comment]
The app, cause it's unable to change ownership.

**Comment by harshavardhana** [comment]
> The app, cause it's unable to change ownership.

Can you point me to the steps so that i can simulate this issue?

**Comment by morph027** [comment]
Basically the same steps like in @holgerstolzenberg script above. Having a Minio, a volume (with `uid` and `gid` set) and then a postgres container, but with data in a subfolder (`PGDATA`) of the mount, cause it can't own the mountpoint anyway.

```
docker service create -d \
  --name postgres \
  --replicas 1 \
  --network postgres-network \
  -p 5432:5432  \
  --mount "type=volume,src=postgres-data,dst=/var/lib/postgresql/data" \
  -e "PGDATA=/var/lib/postgresql/data/pgdata"
  -e "POSTGRES_USER=admin" \
  -e "POSTGRES_PASSWORD=changeit" \
  postgres:alpine
```

**Comment by barrachri** [comment]
this is to reproduce my error:

```
 docker run -p 9000:9000 minio/minio server /export
```

```
docker swarm init
```

```
docker service create \
--mount type=volume,destination=/home/jovyan/work,\
volume-driver=minio/minfs,\
volume-opt=endpoint=http://0.0.0.0:9000,\
volume-opt=access-key=YOURKEY,\
volume-opt=secret-key=YOURSECRECT,\
volume-opt=bucket=test-1,\
volume-opt=uid=1000 \
jupyter/base-notebook:latest
```

then with `docker ps` you find the id of the container and

```
docker exec -it CONTAINER_ID /bin/bash
```

```
touch /home/jovyan/work/ciao
touch: cannot touch 'work/ciao': Permission denied
```

Basically I expect that a user with uid=1000 (like in this case) would be able to write the remote bucket if is mounted with uid=1000.

Should it work in this way?

**Comment by harshavardhana** [comment]
> docker service create -d \
>   --name postgres \
>   --replicas 1 \
>   --network postgres-network \
>   -p 5432:5432  \
>   --mount "type=volume,src=postgres-data,dst=/var/lib/postgresql/data" \
>   -e "PGDATA=/var/lib/postgresql/data/pgdata"
>   -e "POSTGRES_USER=admin" \
>   -e "POSTGRES_PASSWORD=changeit" \
>   postgres:alpine

@morph027 you shouldn't use postgres on MinFS, while the user chowning may be a problem.  MinFS is not going to mimic POSIX entirely and there are no plans on implementing a fully compatibillity. MinFS is meant to be used in simple use cases like serving static web content etc. It is not meant for complex cases like running a database.  You should be using more safer and persistent volumes like portworx in this scenario.

**Comment by harshavardhana** [comment]
> docker service create \
> --mount type=volume,destination=/home/jovyan/work,\
> volume-driver=minio/minfs,\
> volume-opt=endpoint=http://0.0.0.0:9000,\
> volume-opt=access-key=YOURKEY,\
> volume-opt=secret-key=YOURSECRECT,\
> volume-opt=bucket=test-1,\
> volume-opt=uid=1000 \
> jupyter/base-notebook:latest

This is not correct command line @barrachri 

Here is the correct style

For docker-compose.yml 
```
volumes:
  my-test-store:
    driver: minio/minfs
    driver_opts:
      endpoint: https://play.minio.io:9000
      access-key: Q3AM3UQ867SPQQA43P2F
      secret-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      bucket: testbucket
      # opts: "uid=1000,gid=1000" for custom user/group id
```

```
docker service create \
--mount type=volume,destination=/home/jovyan/work,\
volume-driver=minio/minfs,\
volume-opt=endpoint=http://0.0.0.0:9000,\
volume-opt=access-key=YOURKEY,\
volume-opt=secret-key=YOURSECRECT,\
volume-opt=bucket=test-1,\
volume-opt=opts=uid=1000,gid=1000 \
jupyter/base-notebook:latest
```

**Comment by barrachri** [comment]
Thank @harshavardhana!

So I can either create a volume using or use your corrected notation for services?

**Comment by harshavardhana** [comment]
> Thank @harshavardhana!
> 
> So I can either create a named volume or use your corrected notation for services?

Yes @barrachri let us know how it goes.

**Comment by morph027** [comment]
> you shouldn't use postgres on MinFS, while the user chowning may be a problem. MinFS is not going to mimic POSIX entirely and there are no plans on implementing a fully compatibillity. MinFS is meant to be used in simple use cases like serving static web content etc. It is not meant for complex cases like running a database. You should be using more safer and persistent volumes like portworx in this scenario.

@harshavardhana i'm ok with this...was just a test, to see how far i can go with this ;)

**Comment by barrachri** [comment]
@harshavardhana only bad news :/

I create the minio server
```
docker run -p 9000:9000 -d --name minio1 \
-e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" \
-e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
minio/minio server /data
```

then I create a volume
```
docker volume create -d minio/minfs \
  --name share-storage \
  -o endpoint=http://0.0.0.0:9000 \
  -o access-key=AKIAIOSFODNN7EXAMPLE \
  -o secret-key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY \
  -o bucket=test-1 \
  -o opts=uid=1000
```

and a service that will use this volume
```
docker service create \
--mount type=volume,source=share-storage,destination=/home/jovyan/work \
jupyter/base-notebook:latest
```
I connect to the container and it works fine

```
jovyan@11ab357e11f3:~$ ls -al
total 24
drwsrwsr-x 5 jovyan users    8 Sep 22 12:37 .
drwxr-xr-x 3 root   root     3 Aug 26 22:52 ..
-rw-rw-r-- 1 jovyan users  220 Aug 31  2015 .bash_logout
-rw-rw-r-- 1 jovyan users 3771 Aug 31  2015 .bashrc
drwxr-sr-x 3 jovyan users    3 Aug 26 22:53 .conda
drwx--S--- 3 jovyan users    3 Sep 22 12:37 .local
-rw-rw-r-- 1 jovyan users  655 May 16 12:49 .profile
drwxrwxr-x 2 jovyan users    3 Sep 22 07:49 work
jovyan@11ab357e11f3:~$ touch work/ciao
jovyan@11ab357e11f3:~$
```

But if I create the service and declare the volume at the same time
```
docker service create \
--mount type=volume,destination=/home/jovyan/work,\
volume-driver=minio/minfs,\
volume-opt=endpoint=http://0.0.0.0:9000,\
volume-opt=access-key=AKIAIOSFODNN7EXAMPLE,\
volume-opt=secret-key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY,\
volume-opt=bucket=test-1,\
volume-opt=opts=uid=1000 \
jupyter/base-notebook:latest
```

I get this:
```
jovyan@f3db9478b437:~$ ls -al
total 24
drwsrwsr-x 5 jovyan users    8 Sep 22 12:35 .
drwxr-xr-x 3 root   root     3 Aug 26 22:52 ..
-rw-rw-r-- 1 jovyan users  220 Aug 31  2015 .bash_logout
-rw-rw-r-- 1 jovyan users 3771 Aug 31  2015 .bashrc
drwxr-sr-x 3 jovyan users    3 Aug 26 22:53 .conda
drwx--S--- 3 jovyan users    3 Sep 22 12:35 .local
-rw-rw-r-- 1 jovyan users  655 May 16 12:49 .profile
dr-xr-xr-x 0 root   root     0 Aug 30  1754 work
jovyan@f3db9478b437:~$ touch work/ciao
touch: cannot touch 'work/ciao': Permission denied
jovyan@f3db9478b437:~$
```

The plugin doens't pass correctly uid to the volume I guess.

**Comment by barrachri** [comment]
Just to add more context:

Inspect of the service that DOESN'T WORK
```
[
    {
        "ID": "mm4d9rsjshp71ihp95pv80p5l",
        "Version": {
            "Index": 286702
        },
        "CreatedAt": "2017-09-22T12:34:54.492812829Z",
        "UpdatedAt": "2017-09-22T12:34:54.492812829Z",
        "Spec": {
            "Name": "hardcore_noyce",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "jupyter/base-notebook:latest@sha256:fb5358b9535a71da470f240a2e461d37593fc5cea008d99b4a35a782f579b3c4",
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Target": "/home/jovyan/work",
                            "VolumeOptions": {
                                "DriverConfig": {
                                    "Name": "minio/minfs",
                                    "Options": {
                                        "access-key": "AKIAIOSFODNN7EXAMPLE",
                                        "bucket": "test-1",
                                        "endpoint": "http://0.0.0.0:9000",
                                        "opts": "uid=1000",
                                        "secret-key": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
                                    }
                                }
                            }
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        }
                    ]
                },
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {}
        }
    }
]
```

Inspect of the service that work
```
[
    {
        "ID": "bv9gh0ann4pvi89jr23tz5acu",
        "Version": {
            "Index": 286710
        },
        "CreatedAt": "2017-09-22T12:37:49.395174893Z",
        "UpdatedAt": "2017-09-22T12:37:49.395174893Z",
        "Spec": {
            "Name": "practical_gates",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "jupyter/base-notebook:latest@sha256:fb5358b9535a71da470f240a2e461d37593fc5cea008d99b4a35a782f579b3c4",
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Source": "share-storage",
                            "Target": "/home/jovyan/work"
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        }
                    ]
                },
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {}
        }
    }
]
```

Volume inspect for the working service
```
[
    {
        "Driver": "minio/minfs:latest",
        "Labels": {},
        "Mountpoint": "/mnt/share-storage",
        "Name": "share-storage",
        "Options": {
            "access-key": "AKIAIOSFODNN7EXAMPLE",
            "bucket": "test-1",
            "endpoint": "http://0.0.0.0:9000",
            "opts": "uid=1000",
            "secret-key": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        },
        "Scope": "local"
    }
]
```
