### ISSUE TITLE
Deprecate MinFS project

### ISSUE THREAD

**Issue by harshavardhana** [minio/minfs#60]
Mention https://github.com/codedellemc/rexray/tree/master/.docker/plugins/s3fs and http://hub.docker.com/r/rexray/s3fs as better alternatives.

More actively maintained and supported.

**Comment by harshavardhana** [comment]
https://gist.github.com/harshavardhana/0055fc7879e82fd6ebdfb3064109881f should be sufficient for users to use mounted FS with minio. MinFS is no longer needed.

**Comment by TuanAnhBien** [comment]
Hi @harshavardhana , i got a problem when run command: `sudo rexray volume mount testbucket444`, like below:
`FATA[0000] error mounting volume                         error=open testbucket444: no such file or directory volume=testbucket444`

I'm using:
 - rexray v0.10.2, 
 - docker v1.13.1
 - ubuntu 14.04

**Comment by barrachri** [comment]
Hi, so this project is not supported anymore?

**Comment by harshavardhana** [comment]
Yes we are evaluating alternatives at this time. Once we figured it out this project will be deprecated.

**Comment by barrachri** [comment]
I was checking rexray, but it seems it doesn't support connecting to multiple s3 accounts for example.

Wouldn't make more sense to drop minfs but keep to docker plugin using s3fs?

**Comment by harshavardhana** [comment]
Yes that would be a feature request .. that you may have to ask rexray team to introduce in their plugin.

We would like to keep projects which can be actively maintained or are being actively maintained. Currently MinFS is just not there yet and it is competing on features from s3fs with duplicated effort.

**Comment by Sovetnikov** [comment]
@harshavardhana have you recipe for connecting minio to container with rexray/s3fs docker plugin?
Seems there is no endpoint configuration when using it as a plugin.

**Comment by harshavardhana** [comment]
> @harshavardhana have you recipe for connecting minio to container with rexray/s3fs docker plugin?
> Seems there is no endpoint configuration when using it as a plugin.

@Sovetnikov https://github.com/codedellemc/rexray/pull/1042 S3FS_ENDPOINT was merged recently, so should be available in next release perhaps. 

Once its done we will bring in a new recipe/blog post at that point we will deprecate..

**Comment by Sovetnikov** [comment]
Thanks @harshavardhana.
Solution with docker-compose volume configuration would be great too.
