### ISSUE TITLE
How do I install the plugin "4533457"?

### ISSUE THREAD

**Issue by mark-avdeev** [minio/minfs#61]
Link "MinFS Docker volume plugin" is broken and returninig 404 error
https://github.com/minio/minfs/tree/master/docker-plugin

`docker plugin install minio/minfs`

Error response from daemon: pull access denied for minio/minfs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by harshavardhana** [comment]
docker plugin is deprecated @mark-avdeev and not supported anymore
