### ISSUE TITLE
Can we delete some cache generated by minfs？

### ISSUE THREAD

**Issue by thuzhaozhao** [minio/minfs#66]
Hi,

Following minfs readMe, we successfully mounted mybucket  using " https://play.min.io/mybucket /mnt/mounted/mybucket minfs defaults,cache=/tmp/mybucket 0 0".  Then we tried to copy some file to the mount path, here we noticed that the cache seemed to be bigger and bigger. So we have a question: can we delete some cache, likely the cache generated 3days ago? (Seems besides cache.db, we have many files named like 373036323332333338、343133303535323838）

Thanks a lot for your kindly help.

**Comment by harshavardhana** [comment]
@thuzhaozhao  this project is not taking any more feature requests at this point in time - feel free to send a PR. We may get back to the issues any time soon.
