### ISSUE TITLE
file /var/log/minfs.pid

### ISSUE THREAD

**Issue by jimisan** [minio/minfs#67]
Greetings!

```

file /var/log/minfs.pid
/var/log/minfs.pid: ASCII text, with no line terminators

```

why is it not ```/run ``` directory for a pid file.

Can I optionally specify the path to the file?

**Comment by harshavardhana** [comment]
@jimisan this project is not taking any more feature requests at this point in time - feel free to send a PR. We may get back to the issues any time soon.
