### ISSUE TITLE
fuse: Migrate to go-fuse

### ISSUE THREAD

**Issue by harshavardhana** [minio/minfs#7]
Migrate to use using native FUSE module - https://github.com/hanwen/go-fuse

**Comment by pascalandy** [comment]
Great!

**Comment by gjonespf** [comment]
Another interesting possibility might be using:
https://github.com/billziss-gh/cgofuse
Reason being:
- Works on OSX, Linux, Windows
- Native tools for mounting as drive on OSX (OSXFUSE)  / Windows (WinFSP)
Not sure how performance measures up to the OP lib.

**Comment by harshavardhana** [comment]
> Another interesting possibility might be using:
> https://github.com/billziss-gh/cgofuse
> Reason being:

nice alternative @gjonespf

**Comment by harshavardhana** [comment]
We decided to not move to go-fuse, currently library is fine and works.  Closing this bug.
